---

  - script: swarm-init.sh {{ inventory_hostname }}
    when: groups.DockerManagement[0] == inventory_hostname

  - script: swarm-token.py "manager"
    register: docker_managment_token
    when: groups.DockerManagement[0] == inventory_hostname

  - shell: 'if [[ $(docker info 2>&1) == *"Swarm: active"* ]]; then echo "active"; fi'
    register: is_active

  - shell: docker swarm join --token {{ hostvars[groups.DockerManagement[0]].docker_managment_token.stdout_lines[0] }} {{ groups.DockerManagement[0] }}:2377
    when: (groups.DockerManagement[0] != inventory_hostname) and (is_active.stdout != "active")
